### ISSUE TITLE
Choose database

### ISSUE THREAD

**Issue by mmalecki** [Relief-1/Relief1#12]
As IRC logs are pretty volatile, I feel that we may want a discussion here.
# Possiblities
- [Riak](http://wiki.basho.com/)
- [MongoDB](http://www.mongodb.org/)
- [couchbase](http://www.couchbase.com/)
- [geocouch](https://github.com/couchbase/geocouch) (for geo)
- [CouchDB](http://couchdb.apache.org/)
## [Riak](http://wiki.basho.com/)
- no SPOF ([replication](http://wiki.basho.com/Replication.html))
- [HTTP API](http://wiki.basho.com/HTTP-API.html)
- [MapReduce](http://wiki.basho.com/MapReduce.html) (do we need it?)
## [MongoDB](http://www.mongodb.org/)
- fast!
- No SPOF ([sharding](http://www.mongodb.org/display/DOCS/Sharding+Introduction))
- [MapReduce](http://www.mongodb.org/display/DOCS/MapReduce)
- [Simple REST interface](http://www.mongodb.org/display/DOCS/Http+Interface)
## all couch-based stores
- no SPOF (master-master replication)
- HTTP Interface
- can talk to Android devices
- true offline/device sync
- may end up taking enormous amount of disk space (we may compact it, though)
- MapReduce
- user management
- can host web apps directly (npm)
- [attachments](http://wiki.apache.org/couchdb/HTTP_Document_API#Attachments)
## [geocouch](https://github.com/couchbase/geocouch)
- all of the above
- designed specifically for geo data

I would like to see some discussion here. @AvianFlu, which one do you guys at nodejitsu prefer? 
Also, hurry up. I bet we all want to start coding.

If you feel like, I may turn it into a wiki page.

**Comment by cleffen** [comment]
Couchbase for user accounts, profiles, and geolocation
